### ISSUE TITLE
consent for the updated license

### ISSUE THREAD

**Issue by etosch** [SurveyMan/SMPy#19]
@jwnewman @mmcmahon13 @jjfiv @emeryberger 
I am updating the license from CRAPL to Apache 2.0. Technically, I'm supposed to notify everyone who has contributed and obtain consent. Voice consent here.

**Comment by jjfiv** [comment]
You can re-license my commits.

**Comment by emeryberger** [comment]
Seems like a downgrade to me but whatever..

## 

Professor Emery Berger
College of Information and Computer Sciences
University of Massachusetts Amherst
www.emeryberger.org

**Comment by jwnewman** [comment]
I consent to the license change.

**Comment by etosch** [comment]
@mmcmahon13 ?

**Comment by mmcmahon13** [comment]
Sorry, i haven't been checking this email. I consent
